include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "android/**"
    - "assets/**"
    - "build/**"
    - "config/**"
    - "core/**"
    - "res/**"
    - "ios/**"
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"
    - "**/generated/*"
    - "**/*.gr.dart"
  errors:
    avoid_dynamic_calls: error
    avoid_empty_else: error
    avoid_returning_null_for_future: error
    avoid_slow_async_io: warning
    avoid_type_to_string: warning
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    comment_references: warning
    control_flow_in_finally: warning
    empty_statements: warning
    hash_and_equals: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: warning
    no_duplicate_case_values: error
    prefer_void_to_null: error
    test_types_in_equals: warning
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    unsafe_html: error
    valid_regexps: warning
    unnecessary_const: warning
    unnecessary_late: warning
    always_declare_return_types: error
    always_require_non_null_named_parameters: warning
    annotate_overrides: error
    avoid_annotating_with_dynamic: info
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_catches_without_on_clauses: info
    avoid_catching_errors: info
    avoid_equals_and_hash_code_on_mutable_classes: info
    avoid_escaping_inner_quotes: info
    avoid_field_initializers_in_const_classes: info
    avoid_function_literals_in_foreach_calls: info
    avoid_implementing_value_types: info
    avoid_init_to_null: info
    avoid_js_rounded_ints: info
    avoid_null_checks_in_equality_operators: info
    avoid_positional_boolean_parameters: info
    avoid_private_typedef_functions: info
    avoid_redundant_argument_values: info
    avoid_renaming_method_parameters: info
    avoid_return_types_on_setters: warning
    avoid_returning_null: error
    avoid_returning_null_for_void: info
    avoid_returning_this: info
    avoid_setters_without_getters: error
    avoid_shadowing_type_parameters: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_on_closure_parameters: warning
    avoid_unused_constructor_parameters: warning
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: info
    camel_case_types: info
    cascade_invocations: info
    constant_identifier_names: error
    curly_braces_in_flow_control_structures: info
    deprecated_consistency: info
    directives_ordering: info
    empty_catches: info
    empty_constructor_bodies: info
    exhaustive_cases: info
    file_names: warning
    implementation_imports: info
    leading_newlines_in_multiline_strings: info
    library_names: info
    library_prefixes: info
    missing_whitespace_between_adjacent_strings: info
    no_runtimeType_toString: info
    non_constant_identifier_names: info
    null_closures: info
    omit_local_variable_types: info
    only_throw_errors: info
    overridden_fields: info
    package_api_docs: info
    parameter_assignments: info
    prefer_adjacent_string_concatenation: info
    prefer_asserts_in_initializer_lists: info
    prefer_collection_literals: info
    prefer_conditional_assignment: info
    prefer_constructors_over_static_methods: info
    prefer_contains: info
    prefer_equal_for_default_values: info
    prefer_final_fields: info
    prefer_final_in_for_each: info
    prefer_final_locals: info
    prefer_for_elements_to_map_fromIterable: info
    prefer_function_declarations_over_variables: info
    prefer_generic_function_type_aliases: info
    prefer_if_elements_to_conditional_expressions: info
    prefer_if_null_operators: info
    prefer_initializing_formals: info
    prefer_inlined_adds: info
    prefer_interpolation_to_compose_strings: info
    prefer_is_empty: info
    prefer_is_not_empty: info
    prefer_is_not_operator: info
    prefer_iterable_whereType: info
    prefer_mixin: info
    prefer_null_aware_operators: info
    prefer_single_quotes: info
    prefer_spread_collections: info
    prefer_typing_uninitialized_variables: info
    provide_deprecation_message: info
    recursive_getters: info
    slash_for_doc_comments: info
    sort_constructors_first: info
    sort_unnamed_constructors_first: info
    type_annotate_public_apis: info
    type_init_formals: info
    unawaited_futures: info
    unnecessary_await_in_return: info
    unnecessary_brace_in_string_interps: info
    unnecessary_getters_setters: info
    unnecessary_lambdas: info
    unnecessary_new: info
    unnecessary_null_aware_assignments: info
    unnecessary_null_checks: info
    unnecessary_null_in_if_null_operators: info
    unnecessary_nullable_for_final_variable_declarations: info
    unnecessary_overrides: info
    unnecessary_parenthesis: info
    unnecessary_raw_strings: info
    unnecessary_string_escapes: info
    unnecessary_string_interpolations: info
    unnecessary_this: info
    use_function_type_syntax_for_parameters: info
    use_if_null_to_convert_nulls_to_bools: info
    use_is_even_rather_than_modulo: info
    use_named_constants: info
    use_raw_strings: info
    use_rethrow_when_possible: info
    use_setters_to_change_properties: info
    use_string_buffers: info
    use_to_and_as_if_applicable: info
    void_checks: info
    lines_longer_than_80_chars: info
    flutter_style_todos: info
    conditional_uri_does_not_exist: info
    no_leading_underscores_for_library_prefixes: info
    no_leading_underscores_for_local_identifiers: info
    sized_box_shrink_expand: info
    use_decorated_box: warning
    use_colored_box: warning
    unnecessary_null_comparison: ignore

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first: false
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - implementation_imports
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
    - flutter_style_todos
    - conditional_uri_does_not_exist
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - sized_box_shrink_expand
    - use_decorated_box
    - use_colored_box
    # 🔽 Новые правила из второго файла:
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_relative_lib_imports
    - cast_nullable_to_non_nullable
    - depend_on_referenced_packages
    - do_not_use_environment
    - eol_at_end_of_file
    - join_return_with_assignment
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - no_default_cases
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - package_prefixed_library_names
    - prefer_asserts_with_message
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - tighten_type_of_initializing_formals
    - unnecessary_constructor_name
    - use_test_throws_matchers
