name: movie_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
