name: movies_api
description: "Api for Movie Tracker"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
